In [1]:
import pandas as pd
from sklearn.model_selection import StratifiedShuffleSplit
from scipy.stats import skew
from tqdm import tqdm
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("C:\datasets/diabetes.csv")
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [4]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [7]:
X = df.drop('Outcome', axis =1)
X

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [9]:
y = df['Outcome']
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [11]:
X.values, y.values

(array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
        [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
        [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
        ...,
        [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
        [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
        [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]]),
 array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
        0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
        1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 

In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [14]:
X_reshaped = X_scaled.reshape(X_scaled.shape[0], X_scaled.shape[1], 1)
X_reshaped

array([[[ 0.63994726],
        [ 0.84832379],
        [ 0.14964075],
        ...,
        [ 0.20401277],
        [ 0.46849198],
        [ 1.4259954 ]],

       [[-0.84488505],
        [-1.12339636],
        [-0.16054575],
        ...,
        [-0.68442195],
        [-0.36506078],
        [-0.19067191]],

       [[ 1.23388019],
        [ 1.94372388],
        [-0.26394125],
        ...,
        [-1.10325546],
        [ 0.60439732],
        [-0.10558415]],

       ...,

       [[ 0.3429808 ],
        [ 0.00330087],
        [ 0.14964075],
        ...,
        [-0.73518964],
        [-0.68519336],
        [-0.27575966]],

       [[-0.84488505],
        [ 0.1597866 ],
        [-0.47073225],
        ...,
        [-0.24020459],
        [-0.37110101],
        [ 1.17073215]],

       [[-0.84488505],
        [-0.8730192 ],
        [ 0.04624525],
        ...,
        [-0.20212881],
        [-0.47378505],
        [-0.87137393]]])

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_reshaped, y, test_size=0.2, random_state=42)

In [16]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((614, 8, 1), (154, 8, 1), (614,), (154,))

In [17]:
from tensorflow.keras.utils import to_categorical

y_train_encoded = to_categorical(y_train)
y_test_encoded = to_categorical(y_test)

In [18]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# cnn model vary kernel size
from numpy import mean
from numpy import std
from numpy import dstack
from pandas import read_csv
from matplotlib import pyplot
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dropout
from tensorflow.keras import layers, models
from keras.utils import to_categorical

import tensorflow.keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten, Reshape, LSTM, Conv1D, MaxPooling1D
from tensorflow.keras.layers import TimeDistributed, Conv1D, MaxPooling1D

In [19]:
model = Sequential()

model.add(layers.Conv1D(filters=64, kernel_size=2, activation='relu', input_shape=(X_train.shape[1], X_train.shape[2])))
model.add(layers.MaxPooling1D(pool_size=2))
model.add(layers.Conv1D(filters=128, kernel_size=2, activation='relu'))
model.add(layers.MaxPooling1D(pool_size=2))
model.add(Flatten())


model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d (Conv1D)             (None, 7, 64)             192       
                                                                 
 max_pooling1d (MaxPooling1D  (None, 3, 64)            0         
 )                                                               
                                                                 
 conv1d_1 (Conv1D)           (None, 2, 128)            16512     
                                                                 
 max_pooling1d_1 (MaxPooling  (None, 1, 128)           0         
 1D)                                                             
                                                                 
 flatten (Flatten)           (None, 128)               0         
                                                                 
 dense (Dense)               (None, 64)                8

In [20]:
history = model.fit(X_train, y_train, epochs=20, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/20
20/20 [==============================] - 1s 12ms/step - loss: 0.6714 - accuracy: 0.6189 - val_loss: 0.6338 - val_accuracy: 0.6948
Epoch 2/20
20/20 [==============================] - 0s 3ms/step - loss: 0.6147 - accuracy: 0.7036 - val_loss: 0.6056 - val_accuracy: 0.7143
Epoch 3/20
20/20 [==============================] - 0s 4ms/step - loss: 0.5958 - accuracy: 0.7182 - val_loss: 0.5814 - val_accuracy: 0.7078
Epoch 4/20
20/20 [==============================] - 0s 3ms/step - loss: 0.5809 - accuracy: 0.7264 - val_loss: 0.5568 - val_accuracy: 0.7143
Epoch 5/20
20/20 [==============================] - 0s 3ms/step - loss: 0.5530 - accuracy: 0.7313 - val_loss: 0.5320 - val_accuracy: 0.7338
Epoch 6/20
20/20 [==============================] - 0s 3ms/step - loss: 0.5295 - accuracy: 0.7590 - val_loss: 0.5397 - val_accuracy: 0.7532
Epoch 7/20
20/20 [==============================] - 0s 3ms/step - loss: 0.5350 - accuracy: 0.7362 - val_loss: 0.5104 - val_accuracy: 0.7792
Epoch 8/20
20/20 [=

In [21]:
test_loss, test_acc = model.evaluate(X_test, y_test)
print(f'Test accuracy: {test_acc}')

5/5 [==============================] - 0s 2ms/step - loss: 0.5053 - accuracy: 0.7922
Test accuracy: 0.7922077775001526


In [22]:
model_file='C:\datasets/Diabets_CNN.h5'
  
tf.keras.models.save_model(model, model_file, include_optimizer=False)
print('model saved at ', model_file)

model saved at  C:\datasets/Diabets_CNN.h5


In [23]:
from tensorflow.keras.models import load_model

base_model = load_model(model_file)

In [24]:
base_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d (Conv1D)             (None, 7, 64)             192       
                                                                 
 max_pooling1d (MaxPooling1D  (None, 3, 64)            0         
 )                                                               
                                                                 
 conv1d_1 (Conv1D)           (None, 2, 128)            16512     
                                                                 
 max_pooling1d_1 (MaxPooling  (None, 1, 128)           0         
 1D)                                                             
                                                                 
 flatten (Flatten)           (None, 128)               0         
                                                                 
 dense (Dense)               (None, 64)                8

In [25]:
def remove_last_layers(model, num_layers_to_remove):
    # 모델의 레이어를 하나씩 슬라이스해서 앞의 레이어만 가져옴
    model_layers = model.layers[:-num_layers_to_remove]  # 마지막 레이어부터 지정된 갯수만큼 제외
    new_model = models.Sequential(model_layers)  # 새로운 모델에 해당 레이어들만 추가
    return new_model

In [26]:
# 출력층부터 1개의 레이어를 삭제
new_base_model = remove_last_layers(base_model, 1)

In [27]:
# 기존 모델의 층을 동결 (학습되지 않도록 설정)
new_base_model.trainable = False

# 새로운 모델을 정의
new_model = Sequential()

# 기존 모델을 추가
new_model.add(new_base_model)

# 새로운 완전연결층 추가
new_model.add(layers.Dense(64, activation='relu'))  # 기존 출력층 앞의 레이어 대신 추가

# 최종 출력층 추가 (예: 10개의 클래스)
new_model.add(layers.Dense(1))

new_model.compile(optimizer='adam', metrics=['accuracy'], loss='mse')

# 모델 요약 출력
new_model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 sequential_1 (Sequential)   (None, 64)                24960     
                                                                 
 dense_2 (Dense)             (None, 64)                4160      
                                                                 
 dense_3 (Dense)             (None, 1)                 65        
                                                                 
Total params: 29,185
Trainable params: 4,225
Non-trainable params: 24,960
_________________________________________________________________


In [29]:
history2 = model.fit(X_train, y_train, epochs=20, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/20
20/20 [==============================] - 0s 5ms/step - loss: 0.4440 - accuracy: 0.7834 - val_loss: 0.5016 - val_accuracy: 0.7922
Epoch 2/20
20/20 [==============================] - 0s 3ms/step - loss: 0.4452 - accuracy: 0.7834 - val_loss: 0.5092 - val_accuracy: 0.7792
Epoch 3/20
20/20 [==============================] - 0s 3ms/step - loss: 0.4420 - accuracy: 0.7899 - val_loss: 0.5193 - val_accuracy: 0.7597
Epoch 4/20
20/20 [==============================] - 0s 3ms/step - loss: 0.4396 - accuracy: 0.7769 - val_loss: 0.5164 - val_accuracy: 0.7792
Epoch 5/20
20/20 [==============================] - 0s 3ms/step - loss: 0.4454 - accuracy: 0.7948 - val_loss: 0.5062 - val_accuracy: 0.7727
Epoch 6/20
20/20 [==============================] - 0s 3ms/step - loss: 0.4464 - accuracy: 0.7752 - val_loss: 0.5157 - val_accuracy: 0.7662
Epoch 7/20
20/20 [==============================] - 0s 3ms/step - loss: 0.4316 - accuracy: 0.7736 - val_loss: 0.5141 - val_accuracy: 0.7792
Epoch 8/20
20/20 [==

In [30]:
test_loss, test_acc = model.evaluate(X_test, y_test)
print(f'Test accuracy: {test_acc}')

5/5 [==============================] - 0s 2ms/step - loss: 0.5663 - accuracy: 0.7532
Test accuracy: 0.7532467246055603
