In [82]:
from sklearn.datasets import load_breast_cancer
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import seaborn as sns
import tensorflow as tf
from tensorflow import keras

df = pd.read_csv("C:\datasets/abalone.csv", index_col = 0)
df

Sex  Length  Diameter  Height  Whole_weight  Shucked_weight  \
id                                                                 
0      M   0.455     0.365   0.095        0.5140          0.2245   
1      M   0.350     0.265   0.090        0.2255          0.0995   
2      F   0.530     0.420   0.135        0.6770          0.2565   
3      M   0.440     0.365   0.125        0.5160          0.2155   
4      I   0.330     0.255   0.080        0.2050          0.0895   
...   ..     ...       ...     ...           ...             ...   
4172   F   0.565     0.450   0.165        0.8870          0.3700   
4173   M   0.590     0.440   0.135        0.9660          0.4390   
4174   M   0.600     0.475   0.205        1.1760          0.5255   
4175   F   0.625     0.485   0.150        1.0945          0.5310   
4176   M   0.710     0.555   0.195        1.9485          0.9455   

      Viscera_weight  Shell_weight  Rings  
id                                         
0             0.1010        0.1500     15  
1             0.0485        0.0700      7  
2             0.1415        0.2100      9  
3             0.1140        0.1550     10  
4             0.0395        0.0550      7  
...              ...           ...    ...  
4172          0.2390        0.2490     11  
4173          0.2145        0.2605     10  
4174          0.2875        0.3080      9  
4175          0.2610        0.2960     10  
4176          0.3765        0.4950     12  

[4177 rows x 9 columns]

# 베이스라인

In [83]:
for label in "MFI":
    df[label] = df["Sex"] == label
del df["Sex"]

df

Length  Diameter  Height  Whole_weight  Shucked_weight  Viscera_weight  \
id                                                                             
0      0.455     0.365   0.095        0.5140          0.2245          0.1010   
1      0.350     0.265   0.090        0.2255          0.0995          0.0485   
2      0.530     0.420   0.135        0.6770          0.2565          0.1415   
3      0.440     0.365   0.125        0.5160          0.2155          0.1140   
4      0.330     0.255   0.080        0.2050          0.0895          0.0395   
...      ...       ...     ...           ...             ...             ...   
4172   0.565     0.450   0.165        0.8870          0.3700          0.2390   
4173   0.590     0.440   0.135        0.9660          0.4390          0.2145   
4174   0.600     0.475   0.205        1.1760          0.5255          0.2875   
4175   0.625     0.485   0.150        1.0945          0.5310          0.2610   
4176   0.710     0.555   0.195        1.9485          0.9455          0.3765   

      Shell_weight  Rings      M      F      I  
id                                              
0           0.1500     15   True  False  False  
1           0.0700      7   True  False  False  
2           0.2100      9  False   True  False  
3           0.1550     10   True  False  False  
4           0.0550      7  False  False   True  
...            ...    ...    ...    ...    ...  
4172        0.2490     11  False   True  False  
4173        0.2605     10   True  False  False  
4174        0.3080      9   True  False  False  
4175        0.2960     10  False   True  False  
4176        0.4950     12   True  False  False  

[4177 rows x 11 columns]

In [84]:
Y = df['Rings']

X = df.drop('Rings', axis = 1)

In [86]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

## SVC

In [88]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

clf_svm = SVC(random_state = 0)
clf_svm.fit(X_train, y_train)

pred_svm = clf_svm.predict(X_test)

print("\n--- SVM Classifier")
print(accuracy_score(y_test, pred_svm))
print(confusion_matrix(y_test, pred_svm))


--- SVM Classifier
0.24401913875598086
[[ 0  5  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  3  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  4  0 26  3  0  6  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0 31 17  4  9  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 27 29 21 35  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  6 11 48 65  8  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  5 27 83 33  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  2  9 69 40 18  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  2  5 51 41 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  2  3 41 34 13  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  2 21 14 13  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  2 16 10  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  7 11  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  7  

## lf

In [89]:
from sklearn.linear_model import LogisticRegression

clf_lr = LogisticRegression(random_state = 0)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print("\n--- SVM Classifier ---")
print(accuracy_score(y_test, pred_lr))
print(confusion_matrix(y_test, pred_lr))


--- SVM Classifier ---
0.23923444976076555
[[ 0  0  3  3  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2 11  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 30  8  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 24 27  6  5  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 21 36 27 28  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  5 14 59 51  9  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1 11 32 62 42  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  6 17 47 46 22  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  8 15 29 47 22  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  6 31 37 17  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  2 11 20 16  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  3 11 13  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  2  4 11  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1 

c:\users\lee\appdata\local\programs\python\python37\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


# 다중 클래스 분류

In [90]:
# convert age to age group
for ix in df.index:
    row = df.loc[ix]
    if row.Rings <= 8:
        df.loc[ix, 'Rings'] = 'young'
    elif row.Rings >= 11:
        df.loc[ix, 'Rings'] = 'old'
    elif row.Rings >=9 & row.Rings <= 10:
        df.loc[ix, 'Rings'] = 'medium'
        
df.head(5)

Length  Diameter  Height  Whole_weight  Shucked_weight  Viscera_weight  \
id                                                                           
0    0.455     0.365   0.095        0.5140          0.2245          0.1010   
1    0.350     0.265   0.090        0.2255          0.0995          0.0485   
2    0.530     0.420   0.135        0.6770          0.2565          0.1415   
3    0.440     0.365   0.125        0.5160          0.2155          0.1140   
4    0.330     0.255   0.080        0.2050          0.0895          0.0395   

    Shell_weight   Rings      M      F      I  
id                                             
0          0.150     old   True  False  False  
1          0.070   young   True  False  False  
2          0.210  medium  False   True  False  
3          0.155  medium   True  False  False  
4          0.055   young  False  False   True

In [91]:
Y = df['Rings']
Y

id
0          old
1        young
2       medium
3       medium
4        young
         ...  
4172       old
4173    medium
4174    medium
4175    medium
4176       old
Name: Rings, Length: 4177, dtype: object

In [92]:
X = df.drop('Rings', axis = 1)
X

Length  Diameter  Height  Whole_weight  Shucked_weight  Viscera_weight  \
id                                                                             
0      0.455     0.365   0.095        0.5140          0.2245          0.1010   
1      0.350     0.265   0.090        0.2255          0.0995          0.0485   
2      0.530     0.420   0.135        0.6770          0.2565          0.1415   
3      0.440     0.365   0.125        0.5160          0.2155          0.1140   
4      0.330     0.255   0.080        0.2050          0.0895          0.0395   
...      ...       ...     ...           ...             ...             ...   
4172   0.565     0.450   0.165        0.8870          0.3700          0.2390   
4173   0.590     0.440   0.135        0.9660          0.4390          0.2145   
4174   0.600     0.475   0.205        1.1760          0.5255          0.2875   
4175   0.625     0.485   0.150        1.0945          0.5310          0.2610   
4176   0.710     0.555   0.195        1.9485          0.9455          0.3765   

      Shell_weight      M      F      I  
id                                       
0           0.1500   True  False  False  
1           0.0700   True  False  False  
2           0.2100  False   True  False  
3           0.1550   True  False  False  
4           0.0550  False  False   True  
...            ...    ...    ...    ...  
4172        0.2490  False   True  False  
4173        0.2605   True  False  False  
4174        0.3080   True  False  False  
4175        0.2960  False   True  False  
4176        0.4950   True  False  False  

[4177 rows x 10 columns]

In [93]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

## SVC

In [94]:
clf_svm = SVC(random_state = 0)
clf_svm.fit(X_train, y_train)

pred_svm = clf_svm.predict(X_test)

print("\n--- SVM Classifier")
print(accuracy_score(y_test, pred_svm))
print(confusion_matrix(y_test, pred_svm))


--- SVM Classifier
0.6344497607655503
[[174  77  40]
 [126 225  27]
 [105   7 264]]


## lr

In [95]:
clf_lr = LogisticRegression(random_state = 0)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print("\n--- SVM Classifier ---")
print(accuracy_score(y_test, pred_lr))
print(confusion_matrix(y_test, pred_lr))


--- SVM Classifier ---
0.6497607655502392
[[145  79  67]
 [105 236  37]
 [ 68  10 298]]
